name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up .env file with temporary keys for CI/CD
      run: |
        echo "OPENAI_API_KEY=${{secrets.OPENAI_API_KEY }}" >> .env

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-api:latest .

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to DockerHub
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-api:latest

    - name: Run Docker container
      run: docker run -d -p 5001:5000 ${{ secrets.DOCKER_USERNAME }}/flask-api:latest

    - name: Wait for API to be ready
      run: |
        # Wait for up to 30 seconds for the API to be reachable
        for i in {1..30}; do
          if curl -s http://127.0.0.1:5001/; then
            echo "API is up!"
            break
          fi
          echo "Waiting for API..."
          sleep 1
        done

    - name: Run Tests
      run: |
        pytest test_api.py --base-url=http://127.0.0.1:5001