name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up .env file with temporary keys for CI/CD
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

    - name: Build Docker image
      run: docker build -t flaskapi .

    - name: Run Docker container
      run: docker run -d -p 5001:5000 --name flaskapi_container flaskapi

    - name: View Docker logs for troubleshooting
      run: docker logs flaskapi_container

    - name: Wait for API to be ready
      run: |
        for i in {1..60}; do
          if curl -s http://127.0.0.1:5001/; then
            echo "API is up!"
            break
          fi
          echo "Waiting for API..."
          sleep 2
        done

    - name: Run Tests
      run: |
        pytest test_api.py --base-url=http://127.0.0.1:5001

    - name: Stop Docker container
      run: docker stop flaskapi_container

    - name: Remove Docker container
      run: docker rm flaskapi_container